id: P008065
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5168
  title: ཕྱག་ཆེན་སྔོན་འགྲོའི་ཁྲིད་ཡིག་གྲུབ་མཆོག་བླ་མའི་ཞལ་ལུང་།
  author: ''
  volumes:
    08237e859f0c4a7a977d7ca79ee39db5:
      image_group_id: I3CN5170
      title: ''
      volume_number: 1
      total_pages: 174
ebook_metadata:
  title: ཕྱག་ཆེན་སྔོན་འགྲོའི་ཁྲིད་ཡིག་གྲུབ་མཆོག་བླ་མའི་ཞལ་ལུང་།
  author: ''
  sku: P008065
  cover: cover.jpg
  layers:
  - pagination
