id: P008065
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN5168
  title: ཕྱག་ཆེན་སྔོན་འགྲོའི་ཁྲིད་ཡིག་གྲུབ་མཆོག་བླ་མའི་ཞལ་ལུང་།
  author: ''
  volumes:
    cf2a51972d9042b6ac01fbe58255329c:
      image_group_id: I3CN5170
      title: Volume 1 of phyag chen sngon 'gro'i khrid yig grub mchog bla ma'i zhal
        lung /
      volume_number: 1
      total_pages: 174
      base_file: v001.txt
