id: IDB888625
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T09:47:44+00:00'
last_modified: '2022-06-08T18:10:53.004470+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5168
  title: ཕྱག་ཆེན་སྔོན་འགྲོའི་ཁྲིད་ཡིག་གྲུབ་མཆོག་བླ་མའི་ཞལ་ལུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B006:
      image_group_id: I3CN5170
      title: Volume 1 of phyag chen sngon 'gro'i khrid yig grub mchog bla ma'i zhal
        lung /
      total_pages: 174
      order: 1
      base_file: B006.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
